### PR TITLE
More ( readeable / human ) version

### PR DESCRIPTION
**Pull request by Borrajo**
- Added the conversion of integer version to a more readable version for the end user.  
for example: v403701850 now reads v6.1.0.90  

- The minimum version is always v1.0.0

- If there is no bugfix in the version it is not shown. Ex: v1.0.5

### CODE REVIEW

**Comment by evertonstz** [comment]
Thank you for the PR! The function you implemented is exactly what I was going to research next, so you saved me a lot of work!

The problem with using human readable version numbers is that most places use the "non-human readable" version numbering to release their update packages, but some places also use the human readable version numbering, that's why I was looking forward to implement it. 
I'll test your code and merge it, but I'll look into other ways of implementing how the human readable versions are delivered to the user: I'll either return both version numbers to the users or add an option in the settings menu to let the user choose one of the two.

Cheers!

**Comment by Borrajo** [comment]
And if it is written as shown on switchbrew.org?
v403701850 (6.1.0.90)
`v{version}[space]({versionHuman})`

[Example in switchBrew](https://switchbrew.org/wiki/Title_list)

**Comment by evertonstz** [comment]
Seems perfectly fine to me. I'll run some tests later just to be sure. I think I'll end up implementing an option in settings anyway with the 3 displaying types:

- "normal" version numbering;
- "human readable" verion numbering
- the way switchbrew does it, I'll be using this one as default

I'll merge your pull request for now and work over it to implement the above.

**Comment by evertonstz** [comment]
@Borrajo sorry for the late ping, but the project was on hold because I had to do some things in uni.

So, I was testing your changes and it seems I can't get the correct version for some games using your `version_decimal` function. Here are some examples:

Minecraft v2359296
What it's supposed to be: 1.16.201
What I get from the function: 1.2.4

Dead cells v1114112
What it's supposed to be: 1.10.1
What I get from the function: 1.1.1

Hades v262144
What it's supposed to be: 1.0.37119
What I get from the function: 1.0.4

**Comment by Borrajo** [comment]
Sorry for the delay in my response. I was investigating the cases raised and I found many more!
The function I did does not fail, and correctly converts the versions "v123456789" into decimal but many video game creators assign any number to the versions, such as "just dance 2020" uses version 305556.520069
In this link you can see all the latest versions of each game.
[updates list](http://www.benoitren.be/switch-gamepatches.html)

The system I relied on is that of the nintendo switch:
6 bits for the first (highest) number
6 bits for the second (lower) number
4 bits for the third number (micro)
16 bits for bugfixing (buxfig)

If you want to do tests, I created a codepen with both functions.
version -> decimal
decimal -> version
[Codepen](https://codepen.io/borrajo/full/poyWweJ)

It is a shame that not all companies use the standards.

Thank you very much for your support and a very happy new year!

**Comment by evertonstz** [comment]
I see, I reversed your pull request because I had to push some emergencial fixes into production, but I have all the code you contributed and was waiting for your response.

Since the problem seems to be publishers going out of their way to mess with the system and there's really no way we can know the versioning is correct, I think I'll add this in the option and set it off as default. In case the user decides to enable it, I'll just give the user a PSA the human readable versioning could be wrong.

Thank you for the input!

**Pull request merged**
